import "@fontsource/poppins";
import "@/app/css/login.css";
import grovixLog from '@/assets/image/grovix-lab.png';
import Image from 'next/image';
import Link from "next/link";


// export async function getServerSideProps() {
//     return {
//         props: {},
//     };
// }

export const metadata = {
    title: "SignUp / Grovix Lab",
    description: "Generated by Next.js",
};

export default function App() {

    return (
        <>
            <div className="container">
                <form action="/auth/signup" method="post" className="regForm">
                    <div className="inputImage">
                        <img loading="lazy" decoding="async" src={grovixLog.src} alt="" />
                    </div>
                    <div className="inputBox">
                        <input type="text" name="first_name" id="firts_name" placeholder="First Name" />
                    </div>
                    <div className="inputBox">
                        <input type="text" name="last_name" id="last_name" placeholder="Last Name" />
                    </div>
                    <div className="inputBox">
                        <input type="email" name="email" id="email" placeholder="Email" />
                    </div>
                    <div className="inputBox">
                        <input type="number" style={{ borderRadius: "0px", width: "40px" }} name="country_code"
                            id="country_code" placeholder="+91" />
                        &nbsp;
                        <input type="tel" style={{ borderRadius: "0px" }} name="phone" id="phone"
                            placeholder="Phone" />
                    </div>
                    <div className="inputBox" style={{ background: "#f0f0f0" }}>
                        <input type="password" placeholder="Password" name="password" id="password" />
                        <button type="button" id="togglePassword"
                            style={{ marginLeft: "-30px", background: "none", border: "none", cursor: "pointer" }}>
                            👁️
                        </button>
                    </div>
                    <div className="inputText">
                        <input type="checkbox" name="terms_accept" id="terms" />
                        <span>
                            By using our services, you are accepting our <Link href="/terms-of-service" target="_blank">terms
                                of service</Link>.
                        </span>
                    </div>
                    <div className="inputBox">
                        <button>
                            SignUp
                        </button>
                    </div>
                    <div className="inputText">
                        <span>Do you have a account? <Link href="/auth/login">LogIn</Link>.</span>
                    </div>
                </form>
            </div>
            <script
                data-partytown-config
                dangerouslySetInnerHTML={{
                    __html: `document.getElementById('togglePassword').addEventListener('click', function () {
        const passwordInput = document.getElementById('password');
        const type = passwordInput.getAttribute('type') === 'password' ? 'text' : 'password';
        passwordInput.setAttribute('type', type);
        this.textContent = type === 'password' ? '👁️' : '🔒';
    });`,
                }}
            />
        </>
    );
}
